version: "3.8"
services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://db/todo-list
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - todo-list:/data/db
volumes:
  todo-list:
